"""
Graph State Schema for CRAG Workflow.

Defines the TypedDict that maintains state throughout the LangGraph execution.
"""

from typing import TypedDict, List, Literal, Optional, Any


class GraphState(TypedDict):
    """
    State maintained throughout the CRAG workflow.
    
    Attributes:
        question: The user's original query
        documents: List of retrieved text chunks (from vectorstore or web)
        generation: The final answer generated by the LLM
        web_search: Flag indicating if web search is required ("yes"/"no")
        generation_attempts: Counter for generation retry loops
        route_decision: The routing decision ("vectorstore" or "web_search")
    """
    question: str
    documents: List[Any]  # List of Document objects from retrieval.py
    generation: str
    web_search: Literal["yes", "no"]
    generation_attempts: int
    route_decision: Optional[Literal["vectorstore", "web_search"]]
